### ISSUE TITLE
:smiling_face_with_three_hearts: Doesn't render :sad:

### ISSUE THREAD

**Issue by omockler** [asmockler/emoji-as-a-service#16]
<img width="519" alt="screen shot 2019-01-21 at 10 03 59 am" src="https://user-images.githubusercontent.com/176113/51482360-400c6500-1d64-11e9-8ac5-71510e2d25e9.png">

**Comment by asmockler** [comment]
Oh yeah..I was on old OSX when I generated the images before. Should be fixed with caf009655f6af44d20d05dc9ce2d6a154bb6482a
